version: '3'
services:
  teste-habilidade-php:
    build: .
    depends_on:
      - mysql
    ports:
    - 8081:80
    working_dir: /var/www/html
    volumes: 
      - .:/var/www/html
    networks:
      - my_net
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: teste_habilidade_php
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    networks:
      - my_net
networks:
  my_net:
    driver: bridge

